### ISSUE TITLE
Reliability Experiments

### ISSUE THREAD

**Issue by mars203030** [jwkirchenbauer/lm-watermarking#28] opened 2023-11-26 03:41 UTC
Hello,

I am trying to repeat the experiments in the paper and trying to using the figure notes .. but I am not sure what data to extract and how for each note .. I am focusing now in the robustness also it seems the code is not generating or adding any tags to wandb 
I really appreciate you guidance here

Regards

**Comment by jwkirchenbauer** [comment] 2023-11-26 18:44
Unfortunately it's hard to use wandb like we did and have the plotting step be simple to recreate (personally, since I most use the wandb gui not cli). However, if you have run some part of the pipelines and have some data logged to wandb, the "extraction" step is basically just finding the right chart in the visualization view of the wandb project, that basically looks like a poorly labeled and styled version of the curve you want, and then clicking the three dots and "export to csv". 

Then you can see that I had a convention of making a directory with a human readble name (eg. [here](https://github.com/jwkirchenbauer/lm-watermarking/tree/main/watermark_reliability_release/figure_notebooks/figure_data)), and putting the wandb export csv inside of that dir, and pointing the plotting notebooks at these directories to create nicely styled charts.

If you give me a specific experiment and plotted curve you're trying to recreate, I can give more specific instructions w/ screenshots of the wandb chart you're looking for and how to export, download and pull into notebook, which might bootstrap the rest of the reproduction you want to do.

**Comment by mars203030** [comment] 2023-11-26 20:27
thank you .. thank you so much
I am trying to get these

<img width="1004" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/9b13a0d7-8c9a-44ad-91f6-c29720a23711">

<img width="979" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/41fff591-df84-42df-aece-8e475fdc0b7b">

<img width="983" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/85ffa248-4784-4618-815e-850457340cc0">

<img width="797" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/24396f5c-d3c3-430f-8572-90eaf3e26f2d">

**Comment by jwkirchenbauer** [comment] 2023-11-26 21:37
Okay, that's a lot of experiments (nearly all the main paper figures), some of which require different procedures.

Can you give me an example of a command you ran and what data you can see in wandb as a result?
Figure 4 (first screenshot) and the data and models ablation (last screenshot) are the simplest because the figure itself basically shows up in wandb, maybe start with those?

Getting those exact ROC plots and AUC at T plots (second and third screenshots) require a bit of data movement after your download the wandb csv's because what gets logged to wandb by the eval script is the "transpose" of those figures, where there are 4 ROC/AUC charts with 6 lines each, rather than 6 charts with 4 lines each. But I can also help you with those after you're able to get the simpler ones.

**Comment by mars203030** [comment] 2023-11-26 22:00
I am running this code
`RUN_NAME=llama_dipper

GENERATION_OUTPUT_DIR=output2/"$RUN_NAME"

echo "Running generation pipeline with output dir: $GENERATION_OUTPUT_DIR"

python generation_pipeline.py \
    --model_name="meta-llama/Llama-2-7b-hf" \
    --dataset_name=c4 \
    --dataset_config_name=realnewslike \
    --max_new_tokens=200 \
    --min_prompt_tokens=50 \
    --min_generations=10 \
    --input_truncation_strategy=completion_length \
    --input_filtering_strategy=prompt_and_completion_length \
    --output_filtering_strategy=max_new_tokens \
    --seeding_scheme=selfhash \
    --gamma=0.25 \
    --delta=2.0 \
    --run_name="$RUN_NAME"_gen \
    --wandb=True \
    --wandb_project=xyz \
    --verbose=False \
    --output_dir=$GENERATION_OUTPUT_DIR


python attack_pipeline.py \
    --attack_method=dipper \
    --run_name="$RUN_NAME"_dipper_attack \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --verbose=False

python evaluation_pipeline.py \
    --evaluation_metrics=all \
    --run_name="$RUN_NAME"_eval \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --output_dir="$GENERATION_OUTPUT_DIR"_eval \
    --roc_test_stat=all


RUN_NAME=llama_cp

GENERATION_OUTPUT_DIR=output2/"$RUN_NAME"

echo "Running generation pipeline with output dir: $GENERATION_OUTPUT_DIR"
python generation_pipeline.py \
    --model_name="meta-llama/Llama-2-7b-hf" \
    --dataset_name=c4 \
    --dataset_config_name=realnewslike \
    --max_new_tokens=200 \
    --min_prompt_tokens=50 \
    --min_generations=10 \
    --input_truncation_strategy=completion_length \
    --input_filtering_strategy=prompt_and_completion_length \
    --output_filtering_strategy=max_new_tokens \
    --seeding_scheme=selfhash \
    --gamma=0.25 \
    --delta=2.0 \
    --run_name="$RUN_NAME"_gen \
    --wandb=True \
    --wandb_project=xyz \
    --verbose=False \
    --output_dir=$GENERATION_OUTPUT_DIR

python attack_pipeline.py \
    --attack_method=copy-paste \
    --run_name="$RUN_NAME"_cp_attack \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --verbose=False

python evaluation_pipeline.py \
    --evaluation_metrics=all \
    --run_name="$RUN_NAME"_eval \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --output_dir="$GENERATION_OUTPUT_DIR"_eval \
    --roc_test_stat=all

RUN_NAME=llama_gpt

GENERATION_OUTPUT_DIR=output2/"$RUN_NAME"

echo "Running generation pipeline with output dir: $GENERATION_OUTPUT_DIR"
python generation_pipeline.py \
    --model_name="meta-llama/Llama-2-7b-hf" \
    --dataset_name=c4 \
    --dataset_config_name=realnewslike \
    --max_new_tokens=200 \
    --min_prompt_tokens=50 \
    --min_generations=10 \
    --input_truncation_strategy=completion_length \
    --input_filtering_strategy=prompt_and_completion_length \
    --output_filtering_strategy=max_new_tokens \
    --seeding_scheme=selfhash \
    --gamma=0.25 \
    --delta=2.0 \
    --run_name="$RUN_NAME"_gen \
    --wandb=True \
    --wandb_project=xyz \
    --verbose=False \
    --output_dir=$GENERATION_OUTPUT_DIR

python attack_pipeline.py \
    --attack_method=gpt \
    --run_name="$RUN_NAME"_gpt_attack \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --verbose=False

python evaluation_pipeline.py \
    --evaluation_metrics=all \
    --run_name="$RUN_NAME"_eval \
    --wandb=True \
    --input_dir=$GENERATION_OUTPUT_DIR \
    --output_dir="$GENERATION_OUTPUT_DIR"_eval \
    --roc_test_stat=all \
    --evaluation_metrics=detectgpt`

I am getting 108 charts for each attack so I am not sure which one I should consider
for example here for CP attack .. ok I will look for similar ones in wand b

<img width="1434" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/aaf5b47a-0031-4fd3-b571-f599b21f1771">

thanks again for your help

**Comment by mars203030** [comment] 2023-11-26 22:14
for the first one can I get it from those .. this is only for the dipper attack
<img width="937" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/8a547128-c394-4174-87c7-89d882540261">
<img width="470" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/90cf081d-aecf-4e0e-a97a-65fc8b2cf4ce">
<img width="474" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/1db47858-a8b3-4b60-8c18-9af493ee7a5d">
<img width="463" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/275ab00d-8c75-4a63-b122-811982331082">
<img width="484" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/09e7f53b-6368-4aaf-a21d-3772f4a33c74">
<img width="445" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/f9367b07-dc69-49ce-be69-d37b5081a35e">

<img width="461" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/9c0f4aa4-d715-476a-a46d-831094ab23b1">

<img width="467" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/a5c7caae-7545-4973-b79a-c23a90f7b425">

**Comment by jwkirchenbauer** [comment] 2023-11-26 23:36
Few things:
1. For the setup above, since the generation step is the same, i.e. you want to generate a bunch of outputs under a specific set of prompts and watermarking setting, and then you want to apply the dipper, gpt and cp attacks, you only need to run the generation step once! Then after you run the one generation set, you can point each attack command at the output of that one generation run as their input, and then run an eval each on the three attack outputs. (think of it like a root node, with three branches) This will save you a lot of runtime, it's why I separated into stages.
2. Remove the `--evaluation_metrics=detectgpt` from the last eval command. Running the detectgpt method is a bit of an involved process and involves an independent step before the eval command.
3. Your wandb screenshots look reasonable! (sorry there are so many charts) 

For the set of wandb screenshots in your second reply, the ones you probably want are titled:
- w_wm_z_score_at_T aucs
- w_wm_attacked_z_score_at_T aucs

These correspond to the Figure 4 (left), "LeftHash" and (right), "LeftHash Dipper", though the generation sequence lengths in Figure 4 are longer (600, versus your 200).

The naming is roughly f"{text_column}_{detector_type}_at_T aucs", so for the second of the two above this is the "w_wm_attacked" column which is the watermarked generation after attack (using dipper in this case), evaluated using the "z_score" detector method, presented in the AUC @ T format. 

If you have also run the gpt attack or the cp attack, and toggle those runs on in wandb, then you will see them populate in the same "w_wm_attacked_z_score_at_T aucs" chart, which starts to look more like Figure 4 (right).

**Comment by mars203030** [comment] 2023-11-27 00:13
thank you soo much , I really appreciated your help and your time

**Comment by mars203030** [comment] 2023-11-27 00:45
so these two are need for the first figure 
this one left
<img width="378" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/3a3f1a05-ec27-42dc-856d-709d37a75482">
this one right
<img width="369" alt="image" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/146765335/a684ebab-630f-461c-8646-1100d4fbb95c">

for the last figure of model ablation I could use the first image here? if I understood correctly

**Comment by mars203030** [comment] 2023-11-27 02:30
I was able to generate them .. thank you so much

**Comment by jwkirchenbauer** [comment] 2023-11-27 03:17
I think you've got it yea. The first and second images in this last message are similar to figure 4 left, which is unattacked, and figure 4 right, which shows the effect of different attacks.

For the bar charts, those are basically the last datapoint of the AUC @ T curves, i.e. the AUC @ T=200 from your charts, and those are reported separately in wandb as single point measurements and can be visualized as a bar chart using a couple clicks in the wandb gui. 

Let me know if you have further questions, but for now I'll close this issue

**Closed as completed by jwkirchenbauer** 2023-11-27 03:17 UTC
